[package]
name = "block-finder"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.10", features = ["derive"] }
tokio = { version = "1", features = ["macros"] }
ethers = { git = "https://github.com/gakonst/ethers-rs" }
eyre = "0.6.7"

